FROM java:8
VOLUME /home/bytethecloud/
ADD bytethecloud-0.0.1-SNAPSHOT.jar app.jar
RUN bash -c 'touch /app.jar'
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"]

ssh -i ./.ssh/dockeruser dockeruser@13.72.82.13